// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { tables } from "../functions/schema";

export const api = {
  activity: {
    approve: createApiLeaf<"mutation", typeof import("../functions/activity").approve>(convexApi["activity"]["approve"], { auth: "required", type: "mutation" }),
    attachEvidence: createApiLeaf<"mutation", typeof import("../functions/activity").attachEvidence>(convexApi["activity"]["attachEvidence"], { auth: "required", type: "mutation" }),
    bulkAddParticipants: createApiLeaf<"mutation", typeof import("../functions/activity").bulkAddParticipants>(convexApi["activity"]["bulkAddParticipants"], { auth: "required", type: "mutation" }),
    bulkApprove: createApiLeaf<"mutation", typeof import("../functions/activity").bulkApprove>(convexApi["activity"]["bulkApprove"], { auth: "required", type: "mutation" }),
    bulkCreate: createApiLeaf<"mutation", typeof import("../functions/activity").bulkCreate>(convexApi["activity"]["bulkCreate"], { auth: "required", type: "mutation" }),
    bulkDelete: createApiLeaf<"mutation", typeof import("../functions/activity").bulkDelete>(convexApi["activity"]["bulkDelete"], { auth: "required", type: "mutation" }),
    bulkLeave: createApiLeaf<"mutation", typeof import("../functions/activity").bulkLeave>(convexApi["activity"]["bulkLeave"], { auth: "required", type: "mutation" }),
    bulkReject: createApiLeaf<"mutation", typeof import("../functions/activity").bulkReject>(convexApi["activity"]["bulkReject"], { auth: "required", type: "mutation" }),
    count: createApiLeaf<"query", typeof import("../functions/activity").count>(convexApi["activity"]["count"], { auth: "required", type: "query" }),
    create: createApiLeaf<"mutation", typeof import("../functions/activity").create>(convexApi["activity"]["create"], { auth: "required", type: "mutation" }),
    exportAll: createApiLeaf<"mutation", typeof import("../functions/activity").exportAll>(convexApi["activity"]["exportAll"], { auth: "required", type: "mutation" }),
    getMany: createApiLeaf<"query", typeof import("../functions/activity").getMany>(convexApi["activity"]["getMany"], { auth: "required", type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/activity").getOne>(convexApi["activity"]["getOne"], { auth: "required", type: "query" }),
    join: createApiLeaf<"mutation", typeof import("../functions/activity").join>(convexApi["activity"]["join"], { auth: "required", type: "mutation" }),
    leave: createApiLeaf<"mutation", typeof import("../functions/activity").leave>(convexApi["activity"]["leave"], { auth: "required", type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/activity").list>(convexApi["activity"]["list"], { auth: "required", type: "query" }),
    recommended: createApiLeaf<"query", typeof import("../functions/activity").recommended>(convexApi["activity"]["recommended"], { auth: "required", type: "query" }),
    reject: createApiLeaf<"mutation", typeof import("../functions/activity").reject>(convexApi["activity"]["reject"], { auth: "required", type: "mutation" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/activity").remove>(convexApi["activity"]["remove"], { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/activity").update>(convexApi["activity"]["update"], { auth: "required", type: "mutation" }),
  },
  activityLog: {
    getLatest: createApiLeaf<"query", typeof import("../functions/activityLog").getLatest>(convexApi["activityLog"]["getLatest"], { auth: "required", type: "query" }),
  },
  cart: {
    addCart: createApiLeaf<"mutation", typeof import("../functions/cart").addCart>(convexApi["cart"]["addCart"], { auth: "required", type: "mutation" }),
    getCart: createApiLeaf<"query", typeof import("../functions/cart").getCart>(convexApi["cart"]["getCart"], { auth: "required", type: "query" }),
    redeemCart: createApiLeaf<"mutation", typeof import("../functions/cart").redeemCart>(convexApi["cart"]["redeemCart"], { auth: "required", type: "mutation" }),
    removeCartItem: createApiLeaf<"mutation", typeof import("../functions/cart").removeCartItem>(convexApi["cart"]["removeCartItem"], { auth: "required", type: "mutation" }),
    updateCartItemQuantity: createApiLeaf<"mutation", typeof import("../functions/cart").updateCartItemQuantity>(convexApi["cart"]["updateCartItemQuantity"], { auth: "required", type: "mutation" }),
  },
  employee: {
    bulkDelete: createApiLeaf<"mutation", typeof import("../functions/employee").bulkDelete>(convexApi["employee"]["bulkDelete"], { auth: "required", type: "mutation" }),
    bulkImport: createApiLeaf<"mutation", typeof import("../functions/employee").bulkImport>(convexApi["employee"]["bulkImport"], { auth: "required", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/employee").create>(convexApi["employee"]["create"], { auth: "required", type: "mutation" }),
    exportAll: createApiLeaf<"mutation", typeof import("../functions/employee").exportAll>(convexApi["employee"]["exportAll"], { auth: "required", type: "mutation" }),
    getMany: createApiLeaf<"query", typeof import("../functions/employee").getMany>(convexApi["employee"]["getMany"], { auth: "required", type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/employee").getOne>(convexApi["employee"]["getOne"], { auth: "required", type: "query" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/employee").remove>(convexApi["employee"]["remove"], { auth: "required", type: "mutation" }),
    search: createApiLeaf<"query", typeof import("../functions/employee").search>(convexApi["employee"]["search"], { auth: "required", type: "query" }),
    update: createApiLeaf<"mutation", typeof import("../functions/employee").update>(convexApi["employee"]["update"], { auth: "required", type: "mutation" }),
  },
  leaderboard: {
    getMany: createApiLeaf<"query", typeof import("../functions/leaderboard").getMany>(convexApi["leaderboard"]["getMany"], { auth: "required", type: "query" }),
    getMyEntry: createApiLeaf<"query", typeof import("../functions/leaderboard").getMyEntry>(convexApi["leaderboard"]["getMyEntry"], { auth: "required", type: "query" }),
  },
  news: {
    bulkDelete: createApiLeaf<"mutation", typeof import("../functions/news").bulkDelete>(convexApi["news"]["bulkDelete"], { auth: "required", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/news").create>(convexApi["news"]["create"], { auth: "required", type: "mutation" }),
    getLatest: createApiLeaf<"query", typeof import("../functions/news").getLatest>(convexApi["news"]["getLatest"], { auth: "required", type: "query" }),
    getList: createApiLeaf<"query", typeof import("../functions/news").getList>(convexApi["news"]["getList"], { auth: "required", type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/news").getOne>(convexApi["news"]["getOne"], { auth: "required", type: "query" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/news").remove>(convexApi["news"]["remove"], { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/news").update>(convexApi["news"]["update"], { auth: "required", type: "mutation" }),
  },
  redemption: {
    getMany: createApiLeaf<"query", typeof import("../functions/redemption").getMany>(convexApi["redemption"]["getMany"], { auth: "required", type: "query" }),
    getManyAdmin: createApiLeaf<"query", typeof import("../functions/redemption").getManyAdmin>(convexApi["redemption"]["getManyAdmin"], { auth: "required", type: "query" }),
    reviewRedemption: createApiLeaf<"mutation", typeof import("../functions/redemption").reviewRedemption>(convexApi["redemption"]["reviewRedemption"], { auth: "required", type: "mutation" }),
    updateShippingStatus: createApiLeaf<"mutation", typeof import("../functions/redemption").updateShippingStatus>(convexApi["redemption"]["updateShippingStatus"], { auth: "required", type: "mutation" }),
  },
  reward: {
    bulkCreate: createApiLeaf<"mutation", typeof import("../functions/reward").bulkCreate>(convexApi["reward"]["bulkCreate"], { type: "mutation" }),
    bulkDelete: createApiLeaf<"mutation", typeof import("../functions/reward").bulkDelete>(convexApi["reward"]["bulkDelete"], { auth: "required", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/reward").create>(convexApi["reward"]["create"], { auth: "required", type: "mutation" }),
    exportAll: createApiLeaf<"mutation", typeof import("../functions/reward").exportAll>(convexApi["reward"]["exportAll"], { auth: "required", type: "mutation" }),
    getList: createApiLeaf<"query", typeof import("../functions/reward").getList>(convexApi["reward"]["getList"], { auth: "required", type: "query" }),
    getMany: createApiLeaf<"query", typeof import("../functions/reward").getMany>(convexApi["reward"]["getMany"], { auth: "required", limit: 10, type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/reward").getOne>(convexApi["reward"]["getOne"], { auth: "required", type: "query" }),
    getRecommend: createApiLeaf<"query", typeof import("../functions/reward").getRecommend>(convexApi["reward"]["getRecommend"], { auth: "required", type: "query" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/reward").remove>(convexApi["reward"]["remove"], { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/reward").update>(convexApi["reward"]["update"], { auth: "required", type: "mutation" }),
  },
  seed: {
    seedActivity: createApiLeaf<"action", typeof import("../functions/seed").seedActivity>(convexApi["seed"]["seedActivity"], { auth: "optional", type: "action" }),
    seedEmployee: createApiLeaf<"action", typeof import("../functions/seed").seedEmployee>(convexApi["seed"]["seedEmployee"], { auth: "optional", type: "action" }),
    seedReward: createApiLeaf<"action", typeof import("../functions/seed").seedReward>(convexApi["seed"]["seedReward"], { auth: "optional", type: "action" }),
  },
  transaction: {
    approve: createApiLeaf<"mutation", typeof import("../functions/transaction").approve>(convexApi["transaction"]["approve"], { auth: "required", type: "mutation" }),
    bulkApprove: createApiLeaf<"mutation", typeof import("../functions/transaction").bulkApprove>(convexApi["transaction"]["bulkApprove"], { auth: "required", type: "mutation" }),
    comment: createApiLeaf<"mutation", typeof import("../functions/transaction").comment>(convexApi["transaction"]["comment"], { auth: "required", type: "mutation" }),
    exportAll: createApiLeaf<"mutation", typeof import("../functions/transaction").exportAll>(convexApi["transaction"]["exportAll"], { auth: "required", type: "mutation" }),
    feeds: createApiLeaf<"query", typeof import("../functions/transaction").feeds>(convexApi["transaction"]["feeds"], { auth: "required", limit: 10, type: "query" }),
    getMany: createApiLeaf<"query", typeof import("../functions/transaction").getMany>(convexApi["transaction"]["getMany"], { auth: "required", type: "query" }),
    getMonthlyQuestProgress: createApiLeaf<"query", typeof import("../functions/transaction").getMonthlyQuestProgress>(convexApi["transaction"]["getMonthlyQuestProgress"], { auth: "required", type: "query" }),
    getMonthlyTransferQuota: createApiLeaf<"query", typeof import("../functions/transaction").getMonthlyTransferQuota>(convexApi["transaction"]["getMonthlyTransferQuota"], { auth: "required", type: "query" }),
    like: createApiLeaf<"mutation", typeof import("../functions/transaction").like>(convexApi["transaction"]["like"], { auth: "required", type: "mutation" }),
    send: createApiLeaf<"mutation", typeof import("../functions/transaction").send>(convexApi["transaction"]["send"], { auth: "required", type: "mutation" }),
  },
  upload: {
    generateUploadUrl: createApiLeaf<"mutation", typeof import("../functions/upload").generateUploadUrl>(convexApi["upload"]["generateUploadUrl"], { auth: "required", type: "mutation" }),
    getFileUrl: createApiLeaf<"query", typeof import("../functions/upload").getFileUrl>(convexApi["upload"]["getFileUrl"], { auth: "required", type: "query" }),
  },
  user: {
    getCurrentUser: createApiLeaf<"query", typeof import("../functions/user").getCurrentUser>(convexApi["user"]["getCurrentUser"], { auth: "required", type: "query" }),
  },
  wallet: {
    dailyBonusHistory: createApiLeaf<"query", typeof import("../functions/wallet").dailyBonusHistory>(convexApi["wallet"]["dailyBonusHistory"], { auth: "required", type: "query" }),
    dailyLogin: createApiLeaf<"mutation", typeof import("../functions/wallet").dailyLogin>(convexApi["wallet"]["dailyLogin"], { auth: "required", type: "mutation" }),
    getOne: createApiLeaf<"query", typeof import("../functions/wallet").getOne>(convexApi["wallet"]["getOne"], { auth: "required", type: "query" }),
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
