// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { tables } from "../functions/schema";

export const api = {
  activity: {
    getMany: createApiLeaf<"query", typeof import("../functions/activity").getMany>(convexApi["activity"]["getMany"], { limit: 10, type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/activity").getOne>(convexApi["activity"]["getOne"], { type: "query" }),
    join: createApiLeaf<"mutation", typeof import("../functions/activity").join>(convexApi["activity"]["join"], { auth: "required", type: "mutation" }),
    leave: createApiLeaf<"mutation", typeof import("../functions/activity").leave>(convexApi["activity"]["leave"], { auth: "required", type: "mutation" }),
  },
  cart: {
    addCart: createApiLeaf<"mutation", typeof import("../functions/cart").addCart>(convexApi["cart"]["addCart"], { auth: "required", type: "mutation" }),
    getCart: createApiLeaf<"query", typeof import("../functions/cart").getCart>(convexApi["cart"]["getCart"], { auth: "required", type: "query" }),
    redeemCart: createApiLeaf<"mutation", typeof import("../functions/cart").redeemCart>(convexApi["cart"]["redeemCart"], { auth: "required", type: "mutation" }),
    removeCartItem: createApiLeaf<"mutation", typeof import("../functions/cart").removeCartItem>(convexApi["cart"]["removeCartItem"], { auth: "required", type: "mutation" }),
    updateCartItemQuantity: createApiLeaf<"mutation", typeof import("../functions/cart").updateCartItemQuantity>(convexApi["cart"]["updateCartItemQuantity"], { auth: "required", type: "mutation" }),
  },
  employee: {
    search: createApiLeaf<"query", typeof import("../functions/employee").search>(convexApi["employee"]["search"], { auth: "required", type: "query" }),
  },
  leaderboard: {
    getMany: createApiLeaf<"query", typeof import("../functions/leaderboard").getMany>(convexApi["leaderboard"]["getMany"], { auth: "required", type: "query" }),
    getMyEntry: createApiLeaf<"query", typeof import("../functions/leaderboard").getMyEntry>(convexApi["leaderboard"]["getMyEntry"], { auth: "required", type: "query" }),
  },
  redemption: {
    getMany: createApiLeaf<"query", typeof import("../functions/redemption").getMany>(convexApi["redemption"]["getMany"], { auth: "required", limit: 20, type: "query" }),
    reviewRedemption: createApiLeaf<"mutation", typeof import("../functions/redemption").reviewRedemption>(convexApi["redemption"]["reviewRedemption"], { auth: "required", type: "mutation" }),
  },
  reward: {
    getMany: createApiLeaf<"query", typeof import("../functions/reward").getMany>(convexApi["reward"]["getMany"], { auth: "required", limit: 10, type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/reward").getOne>(convexApi["reward"]["getOne"], { auth: "required", type: "query" }),
    getRecommend: createApiLeaf<"query", typeof import("../functions/reward").getRecommend>(convexApi["reward"]["getRecommend"], { auth: "required", type: "query" }),
    getTrending: createApiLeaf<"query", typeof import("../functions/reward").getTrending>(convexApi["reward"]["getTrending"], { auth: "required", type: "query" }),
  },
  seed: {
    seedActivity: createApiLeaf<"action", typeof import("../functions/seed").seedActivity>(convexApi["seed"]["seedActivity"], { auth: "optional", type: "action" }),
    seedEmployee: createApiLeaf<"action", typeof import("../functions/seed").seedEmployee>(convexApi["seed"]["seedEmployee"], { auth: "optional", type: "action" }),
    seedReward: createApiLeaf<"action", typeof import("../functions/seed").seedReward>(convexApi["seed"]["seedReward"], { auth: "optional", type: "action" }),
  },
  transaction: {
    approve: createApiLeaf<"mutation", typeof import("../functions/transaction").approve>(convexApi["transaction"]["approve"], { auth: "required", type: "mutation" }),
    comment: createApiLeaf<"mutation", typeof import("../functions/transaction").comment>(convexApi["transaction"]["comment"], { auth: "required", type: "mutation" }),
    feeds: createApiLeaf<"query", typeof import("../functions/transaction").feeds>(convexApi["transaction"]["feeds"], { auth: "required", limit: 10, type: "query" }),
    getHistory: createApiLeaf<"query", typeof import("../functions/transaction").getHistory>(convexApi["transaction"]["getHistory"], { auth: "required", type: "query" }),
    like: createApiLeaf<"mutation", typeof import("../functions/transaction").like>(convexApi["transaction"]["like"], { auth: "required", type: "mutation" }),
    send: createApiLeaf<"mutation", typeof import("../functions/transaction").send>(convexApi["transaction"]["send"], { auth: "required", type: "mutation" }),
  },
  user: {
    getCurrentUser: createApiLeaf<"query", typeof import("../functions/user").getCurrentUser>(convexApi["user"]["getCurrentUser"], { auth: "required", type: "query" }),
  },
  wallet: {
    getOne: createApiLeaf<"query", typeof import("../functions/wallet").getOne>(convexApi["wallet"]["getOne"], { auth: "required", type: "query" }),
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
