import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const googleSans = localFont({
  src: [
    {
      path: "../../public/GoogleSans-Regular.woff2",
      weight: "400",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", googleSans.className)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
