import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Providers } from "@/components/providers";
import { routing } from "@/i18n/routing";
import { cn } from "@/lib/utils";

const googleSans = localFont({
  src: [
    {
      path: "../../../public/GoogleSans-Regular.woff2",
      weight: "400",
    },
    {
      path: "../../../public/GoogleSans-Medium.woff2",
      weight: "500",
    },
    {
      path: "../../../public/GoogleSans-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "../../../public/GoogleSans-Bold.woff2",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "SMART Point",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={cn("h-full antialiased", googleSans.className)}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
